### ISSUE TITLE
Integration of external library (CRY) for cosmic ray generation in DDG4 simulation (Question)

### ISSUE THREAD

**Issue by Shivang-UHM** [AIDASoft/DD4hep#940] opened 2022-08-01 19:51 UTC
OS version: e.g. VBox with Ubuntu 20.04.2 LTS
Compiler version: GCC 9.3
DD4hep version: v01-16-01
Reproduced by: Geant4 10.07p01, ROOT version: 6.22, cmake: 3.16.3

Hello, 

We want to use 3rd party particle generation library [CRY](https://nuclear.llnl.gov/simulation/main.html#:~:text=appropriate%20link%20below.-,CRY,-Generates%20correlated%20cosmic)  for cosmic ray generation in DDG4 simulation.

What would be the best approach to do that? 
Is there any function available to directly call the library from python script, any example available or do we have to modify the G4ParticleGenerator?

Thanks,

Shivang

**Comment by andresailer** [comment] 2022-08-02 11:46
Hi Shivang,

I think you need something like a Geant4EventReader plugin, see attached prototype: [DDCryPlugin.zip](https://github.com/AIDASoft/DD4hep/files/9241836/DDCryPlugin.zip)

Similar to https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4EventReaderGuineaPig.cpp, but instead of reading a file, you call the CRY library.

One has to translate from CRYParticle to Geant4Particle.

Note: I had to add `-fPIC` to the CRY makefile to link the library to DDCryPlugin

Couple questions, comments.

- Does CRY always create single particles? Or also decay chains? Multiple individual particles should not be an issue.
- Random number seeding is not yet implemented.
- DDSim needs a small change to allow a user to set their own input plugin, are you going to use ddsim to run the geant4 simulation?

Cheers,
Andre

**Comment by Shivang-UHM** [comment] 2022-08-04 01:33
Hi Andre,

Thanks for your prompt response.

Do, I have to rebuild the dd4hep with this DDCRYPlugin or build it as an example?

> Does CRY always create single particles? Or also decay chains? Multiple individual particles should not be an issue.
- I think it generates single particle from the cosmic-ray particle shower distribution and associated secondary particles, very much like particle gun.

> DDSim needs a small change to allow a user to set their own input plugin, are you going to use ddsim to run the geant4 simulation?
- I'm playing with both, ddsim and python script. 

Thanks,

Shivang

**Comment by andresailer** [comment] 2022-08-04 09:28
Hi Shivang,

The DDCryPlugin is a standalone package. With the cmake as is, it expects the CRY source code inside the same folder under the name `cry` I think, and the `-fPIC` as mentioned above.
Then make sure the library and components file location is part of LD_LIBRARY_PATH.

Cheers,
Andre

**Comment by andresailer** [comment] 2022-08-11 12:55
Hi @Shivang-UHM ,

Is there anything else you need from our side for this issue?

**Comment by Shivang-UHM** [comment] 2022-08-11 19:50
Hi Andre,

Sorry, I haven't worked on it this week. I'll try this weekend and will update you accordingly.

Thank you

**Comment by andresailer** [comment] 2022-10-28 11:42
Hi @Shivang-UHM 
Is there anything else you need from our side for this issue?

**Comment by saraheno** [comment] 2023-02-08 20:40
> Hi Shivang,
> 
> I think you need something like a Geant4EventReader plugin, see attached prototype: [DDCryPlugin.zip](https://github.com/AIDASoft/DD4hep/files/9241836/DDCryPlugin.zip)
> 
> Similar to https://github.com/AIDASoft/DD4hep/blob/master/DDG4/plugins/Geant4EventReaderGuineaPig.cpp, but instead of reading a file, you call the CRY library.
> 
> One has to translate from CRYParticle to Geant4Particle.
> 
> Note: I had to add `-fPIC` to the CRY makefile to link the library to DDCryPlugin
> 
> Couple questions, comments.
> 
> * Does CRY always create single particles? Or also decay chains? Multiple individual particles should not be an issue.
> * Random number seeding is not yet implemented.
> * DDSim needs a small change to allow a user to set their own input plugin, are you going to use ddsim to run the geant4 simulation?
> 
> Cheers, Andre

Hi Andre

I am not sure where to put the -fPIC into the cry Makefile?  could you post a picture of the Makefile with this added?

**Comment by andresailer** [comment] 2023-02-09 06:04
Should be this change
```diff
diff Makefile.common~ Makefile.common

3c3

< CXXFLAGS += -I.

---

> CXXFLAGS += -fPIC -I.

```

**Comment by saraheno** [comment] 2023-02-09 22:52
> Hi Shivang,
> 
> The DDCryPlugin is a standalone package. With the cmake as is, it expects the CRY source code inside the same folder under the name `cry` I think, and the `-fPIC` as mentioned above. Then make sure the library and components file location is part of LD_LIBRARY_PATH.
> 
> Cheers, Andre

where/how do I "make sure the library and components file location is part of LD_LIBRARY_PATH"?
thank you
Sarah Eno

**Comment by saraheno** [comment] 2023-02-09 22:57
Also Andre I'm sorry but I do not think I have succcessfully figured out how to make the building find DDCry.

My attempt at instructions is at: https://foswiki.web.cern.ch/Calvision/DualCrystalDD4hep#including_the_cosmic_ray_generator

But when I do this, in the build area if I do "grep -r DDCry *", it comes up null, so I don't think my cmake command is correct?  how do I tell it to include that area?

**Comment by andresailer** [comment] 2023-02-10 06:02
After `git clone ...cry.git`
you have to build the cry library first
```
cd cry
make
ls -l lib/libCRY.a  # should exist now
cd ../../
```

DDCryPlugin is standalone, so don't compile it as part of DD4hep or the examples.
Just add the very end after you have DD4hep and your package
something like this
```
git clone https://github.com/saraheno/DDCry.git
cd DDCry
git clone https://github.com/saraheno/cry.git
cd cry
make
cd ..
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=$PWD/install ..
make install
source ../install/bin/thisDDCry.sh
```

**Comment by saraheno** [comment] 2023-02-10 13:53
When you say "stand alone", that means that I cannot use it instead of the particle gun when running ddsim?  I'll instead need to have ddsim ...  hmmm...  it will read some output file produced by DDCry? or?

Also, the "build" area above... that would be a different build area than the one where I build ddsim?  Two very separate areas?  or the same one?

**Comment by andresailer** [comment] 2023-02-13 09:38
"Stand alone" means the package should be compiled by itself, not as part of DD4hep or DD4hep examples. at least not with the CMakeLists.txt it contains. Of course you can adapt the CMakeLists.txt to your liking in this regard, but out of the box this does not work. One could also use FetchContent to compile the cry library (but I needed to change it, and I didn't want to put the source code somewhere else). But all of this is left as an exercise for the user...

ddsim works with DDCry as described in #942 the CRY library will be called to create events on demand.

Yes, the build folder for for DDCry and DD4hep have to be different. DDCry should be outside of the DD4hep directory. But you can modify the CMakeLists.txt as you want and make it part of your singleCrystal package for example

**Comment by saraheno** [comment] 2023-02-14 21:33
I'm sorry Andre, I am still having problems.  If ddsim is going to call DDCry, somehow when I link ddsim it has to somehow find the libraries.  This is the LD_LIBRARY_PATH you mention in your original discussion.  But I don't know how to arrange this.  when I am building ddsim, nornmally I make a build area, do the cmake command, and then do the make command.  do I somehow update LD_LIBRARY_PATH between the cmake and the make to point to the DDCRY libraries?  and how will I find those libraries to know their path?

**Comment by andresailer** [comment] 2023-02-15 09:20
Hi Sarah,
The plugins are loaded at runtime using the DD4hep plugin manager functionality. The plugin manager reads all the *.components it finds in the directories that are part of the LD_LIBRARY_PATH, and if something requests the instantiation of a plugin with a name the corresponding library is loaded and the plugin is instantiated.

Thus if your `source ../install/bin/thisDDCry.sh` (or whatever the path is) it should set up the LD_LIBRARY_PATH correctly.

This DDCry input plugin is no different than your own geometry or sensitive detector plugins (basically everything is a plugin). They are also not linked against DD4hep during linking, but loaded at runtime.

**Comment by saraheno** [comment] 2023-02-15 17:06
okay, so if I run the setup for ddsim and also the setup for DDCry, I should have both in my LD_LIBRARY_PATH

**Comment by saraheno** [comment] 2023-02-15 17:33
Andre:

so, trying to do this, I don't seem to know the magic cmake command for DDCRY.  I am doing:


![image](https://user-images.githubusercontent.com/5215288/219107125-b0f36aa8-491a-4f5c-b68f-877d22ffad3a.png)
 

and when I try to do the cmake, I get

![image](https://user-images.githubusercontent.com/5215288/219107323-2c0f6d12-7e31-4782-bf66-6ef20ed43dba.png)

**Comment by andresailer** [comment] 2023-02-15 18:37
```bash
source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/setup.sh
git clone https://github.com/saraheno/DDCry.git
cd DDCry
git clone https://github.com/saraheno/cry.git

# do not commit object files to git, we need to remove those
rm cry/src/*.o

# compile the CRY library with the same compiler and c++ standard as the rest (gcc 11 defaults to c++ 17)
make -C cry
mkdir build
cd build

# BUILD_TESTING: we have to disable testing because otherwise there is a missing folder
# CMAKE_CXX_STANDARD: there is something wrong in the old DD4hep cmake stuff that causes the CMAKE_CXX_STANDARD to be a bad value
# CMAKE_INSTALL_PREFIX: set install location somewhere sensible
cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=OFF -D CMAKE_CXX_STANDARD=17 -D CMAKE_INSTALL_PREFIX=$PWD/../install ..

make install

```

**Comment by saraheno** [comment] 2023-02-15 18:51
Thanks Andre. that worked.  but then where is the setup command that I need to do in order to add the resulting libraries to my LD_LIBRARY thing?  I guess it is DDCry/build/thisDDCry.sh?  or is it DDCry/install/bin/thisDDCry.sh?

**Comment by saraheno** [comment] 2023-02-15 18:52
or is is DDCry/cry/setup.sh?

**Comment by andresailer** [comment] 2023-02-15 18:58
Like I wrote in https://github.com/AIDASoft/DD4hep/issues/940#issuecomment-1425232969 and https://github.com/AIDASoft/DD4hep/issues/940#issuecomment-1430998942 it is `install/bin/thisDDCry.sh` (wherever else that may be in)

**Comment by saraheno** [comment] 2023-02-15 19:07
Thanks.  then once I follow https://github.com/AIDASoft/DD4hep/pull/942 and put that into my steering, the ddsim command would be

ddsim --steeringFile SCEPCALsteering.py --compact ./DRSingleCrystal.xml --runType batch --part.userParticleHandler=''exampleUserPlugin" -N 1 -O out.root

**Comment by saraheno** [comment] 2023-02-15 19:08
okay, not that... that crashed my window

**Comment by andresailer** [comment] 2023-02-15 19:19
You need a much newer DD4hep than what is part of LCG_101 for that. So try LCG_102b and recompile everything!

**Comment by andresailer** [comment] 2023-02-15 19:35
You are still using LCG_101, you have to use LCG_102b.

**Comment by saraheno** [comment] 2023-02-15 19:35
I don't understand what that means.  what is an LCG and how do I change its version?

**Comment by andresailer** [comment] 2023-02-15 19:37
```
/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/setup.sh
                             ~~~~~~~
```

This is LCG_101

**Comment by saraheno** [comment] 2023-02-15 19:38
so I just have to change 101 to 102b in that directory name?

**Comment by andresailer** [comment] 2023-02-15 19:38
yes

**Comment by andresailer** [comment] 2023-02-15 19:38
And then you have to recompile everything

**Comment by saraheno** [comment] 2023-02-15 19:39
okay, that will take some time...  thanks.

**Comment by saraheno** [comment] 2023-02-15 20:08
now when I do
 ddsim --steeringFile SCEPCALcosmicSteering.py --compact ./DRSingleCrystal.xml --runType batch --part.userParticleHandler="exampleUserPlugin" -N 1 -O out.root

it says

ERROR: Batch mode requested, but did not set inputFile(s) or gun

so I guess it doesn't like my --part.userParticleHandler?

**Comment by saraheno** [comment] 2023-02-16 17:06
oksy, this seems better:   ddsim --steeringFile SCEPCALcosmicSteering.py --compact ./DRSingleCrystal.xml --runType run -N 1 -O out.root

but now I'm getting
![image](https://user-images.githubusercontent.com/5215288/219436916-e1f05a35-82bf-4f02-bfbb-c98721314405.png)

**Comment by saraheno** [comment] 2023-02-16 17:18
okay, I just added those parameters to DRSingleCrystal.xml and it goes further.  It feels odd to do, as my setup doesn't have a tracker, but fine.

but now it seems LCG102b has a different version of GEANT than 101 and my code won't run due to changes in GEANTs optical simulation.  Ah well!

**Comment by saraheno** [comment] 2023-02-16 17:36
okay, I have the optical properties where it runs, but now I get a really weird error
![image](https://user-images.githubusercontent.com/5215288/219442554-14563328-71ac-478b-bf84-af6bb7d63dea.png)
 I have no idea what this is?  My run commands are:

![image](https://user-images.githubusercontent.com/5215288/219444087-78e3c850-6367-4c78-83ce-4375f44b475c.png)

**Comment by andresailer** [comment] 2023-02-16 17:52
Please stop posting screenshots.
Copy and paste of terminal text makes it easier to copy commands or error messages. I don't want to type all those commands to see if I can reproduce your issue.
Thanks for your understanding.

**Comment by MarkusFrankATcernch** [comment] 2023-02-16 17:55
The weird error must be due to double-loading of libraries (your DD4hep and LCG View's DD4hep) and double-instantiation of static storage.
We need some way to reproduce this behavior to debug it.

**Comment by MarkusFrankATcernch** [comment] 2023-02-16 18:03
@andresailer I have some suspicion this is related to the problem we debugged 2 weeks ago related to the symbol resolution in python, where also DD4hep did load all sorts of libraries from the LCG view.

**Comment by saraheno** [comment] 2023-02-16 18:15
okay, here are the commands not in a screen shot

do $ source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh

then create a subdirectory to hold your work

$ mkdir lala

$ cd lala

$ git clone https://github.com/AIDASoft/DD4hep.git
$ cd DD4hep/examples

$ git clone https://github.com/saraheno/SingleDualCrystal.git
$ edit [CMakeLists](https://foswiki.web.cern.ch/bin/edit/Calvision/CMakeLists?topicparent=Calvision.DualCrystalDD4hep).txt and add [SingleDualCrystal](https://foswiki.web.cern.ch/bin/edit/Calvision/SingleDualCrystal?topicparent=Calvision.DualCrystalDD4hep) to
SET([DD4HEP](https://foswiki.web.cern.ch/bin/edit/Calvision/DD4HEP?topicparent=Calvision.DualCrystalDD4hep) _EXAMPLES "AlignDet [CLICSiD](https://foswiki.web.cern.ch/bin/edit/Calvision/CLICSiD?topicparent=Calvision.DualCrystalDD4hep) [ClientTests](https://foswiki.web.cern.ch/bin/edit/Calvision/ClientTests?topicparent=Calvision.DualCrystalDD4hep) Conditions DDCMS DDCodex DDDigi DDG4 DDG4_MySensDet [LHeD](https://foswiki.web.cern.ch/bin/edit/Calvision/LHeD?topicparent=Calvision.DualCrystalDD4hep) [OpticalSurfaces](https://foswiki.web.cern.ch/bin/edit/Calvision/OpticalSurfaces?topicparent=Calvision.DualCrystalDD4hep) Persistency DDCAD [SimpleDetector](https://foswiki.web.cern.ch/bin/edit/Calvision/SimpleDetector?topicparent=Calvision.DualCrystalDD4hep) [SingleDualCrystal](https://foswiki.web.cern.ch/bin/edit/Calvision/SingleDualCrystal?topicparent=Calvision.DualCrystalDD4hep) "CACHE STRING "List of DD4hep Examples to build")
$ cd ..

$mkdir build

$mkdir install

$cd build/

$ cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release -DDD4HEP_BUILD_EXAMPLES=ON ..

$ make -j4

$ make install

$ cd ..

$ source bin/thisdd4hep.sh

then get out of the DD4hep subdirectory of your new subdirectory lala and do

$ git clone https://github.com/saraheno/DDCry.git
$cd DDCry

$ git clone https://github.com/saraheno/cry.git
$ make -C cry

$mkdir build

$cd build

$cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=OFF -D CMAKE_CXX_STANDARD=17 -D CMAKE_INSTALL_PREFIX=$PWD/../install ..

$make

$ make install

$cd ..

$ source install/bin/thisDDCry.sh

now go back to your DD4hep/examples/SingleDualCrystal/compact area (be sure you did the "source bin/thisdd4hep.sh") and do

ddsim --steeringFile [SCEPCALcosmicSteering](https://foswiki.web.cern.ch/bin/edit/Calvision/SCEPCALcosmicSteering?topicparent=Calvision.DualCrystalDD4hep).py --compact ./DRSingleCrystal.xml --runType run -N 1 -O out.root

**Comment by andresailer** [comment] 2023-02-16 18:52
> @andresailer I have some suspicion this is related to the problem we debugged 2 weeks ago related to the symbol resolution in python, where also DD4hep did load all sorts of libraries from the LCG view.

Yeah, the building of DD4hep and using DD4hep from the LCG view are probably causing this.

**Comment by andresailer** [comment] 2023-02-16 19:38
@saraheno Please note https://github.com/saraheno/SingleDualCrystal/pull/2

```
source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh
mkdir lala
cd lala
# don't mix DD4hep into the mix, will also save a ton of time when this is not necessary.
# git clone https://github.com/AIDASoft/DD4hep.git
# cd DD4hep/examples
# fix single crystal to build by itself, see Pull request above
git clone --branch standAlone https://github.com/andresailer/SingleDualCrystal.git
cd SingleDualCrystal
mkdir build
mkdir install
cd build/
cmake -D CMAKE_INSTALL_PREFIX=$PWD/../install ..
make -j4
make install
cd ..
source install/bin/thisSingleCrystal.sh
git clone https://github.com/saraheno/DDCry.git
cd DDCry
git clone https://github.com/saraheno/cry.git
make -C cry
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_TESTING=OFF -D CMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=$PWD/../install ..
make
make install
cd ..
source install/bin/thisDDCry.sh
source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh
# now go back to your SingleDualCrystal/compact area 
cd ../compact
ddsim --steeringFile SCEPCALcosmicSteering.py --compact ./DRSingleCrystal.xml --runType run -N 1 -O out.root
```

Please note that you need to point the CRYEventReader to a setup file for CRY! and replace the paths in your SCEPCALcosmicSteering.py according to the relative location (or make them absolute)
(part of the PR above)
```python
   steeringFile = "../DDCry/cry/test/setup.file"                                                                                                                                                          
   gen.Input = 'CRYEventReader|' + steeringFile                                                                                                                                                           
   gen.Parameters = {'DataFilePath': '../DDCry/cry/data'}
```

**Comment by andresailer** [comment] 2023-02-17 09:22
> now when I do ddsim --steeringFile SCEPCALcosmicSteering.py --compact ./DRSingleCrystal.xml --runType batch --part.userParticleHandler="exampleUserPlugin" -N 1 -O out.root
> 
> it says
> 
> ERROR: Batch mode requested, but did not set inputFile(s) or gun
> 
> so I guess it doesn't like my --part.userParticleHandler?

The `userParticleHandler` is functionality to store MC history after the simulation, it is unrelated to the input plugins we are discussing here. So `--part.userParticleHandler=""` would still be the thing to do (or setting this in your SCEPCALcosmicSteering.py file`

The error about the batch mode and  inputFile is fixed in #1061

**Comment by saraheno** [comment] 2023-02-17 13:43
Thanks, this now compiles and runs!  the muons don't hit my crystal, but that is a problem I think even I can figure out :)

**Comment by andresailer** [comment] 2023-02-17 14:01
Alright! Great and good luck!

**Closed by andresailer** 2023-02-17 14:01 UTC
Labels: enhancement, question, Testing
