### ISSUE TITLE
New visualisation by reference edits alpha value of referenced VisAttr

### ISSUE THREAD

**Issue by simonge** [AIDASoft/DD4hep#1117] opened 2023-05-25 10:56 UTC
Setting the values of a new VisAttr by reference to another by name, then changing some results in the alpha of the original being edited. All other original attributes remain unchanged.

e.g. The alpha of AnlGray is changed to 0.3 by the following line
`
    <vis name="TransparentGray"      alpha="0.3" ref="AnlGray"       showDaughters="true" visible="true"/>`

I believe the problem is in the function `VisAttr::argb` from Objects.cpp
`
alpha = o.alpha;`
may be better as
`
alpha = o.alpha();`

**Comment by simonge** [comment] 2023-05-26 15:15
The bug appears to be more complicated than I thought at first. Trying to further understand my problem

**Comment by MarkusFrankATcernch** [comment] 2023-05-26 15:22
This is far more complex, because VisAttrs are only partially represented in ROOT by TColor.
The reset is embedded in the inheritance structure of TGeoVolume.

This would leave you with a very difficult mechanism to properly update all dependent objects if
you would change alpha as you would like in the code snippet above.

**Comment by MarkusFrankATcernch** [comment] 2023-05-26 15:38
To me it looks like ROOT inherits the transparency from the parent volume.
This means the alpha of a n-level daughter is the product of it's own alpha with all alphas of the parent path.
This makes sense if you think of subdetector (or elements thereof) as individual modules you simply group together.
Anyhow, this would not be addressed by your suggestion.

**Comment by MarkusFrankATcernch** [comment] 2023-07-18 12:05
@simonge What should we do with this issue?
I would propose to close it. There is simply no solution to it. 
The internals of TGeo are simply not prepared to handle visualization attributes like this.
Hence there is nothing one could do here from outside.

**Comment by simonge** [comment] 2023-07-18 12:15
Feel free to close it. I still need to follow up on where the issue is coming from, might be somewhere in ROOT rather than DD4hep. The order/whether detectors are included shouldn't really be able to effect the visualisation of other unrelated detectors.

**Comment by MarkusFrankATcernch** [comment] 2023-07-18 12:20
The order how subdetectors are included should not affect the visualization.
According to my experience it also does not.
What matters however is the hierarchy. 
Alpha values of parents (transparency)  also affects the transparency of the children of these parents.

**Comment by MarkusFrankATcernch** [comment] 2023-07-19 16:27
@simonge  Thanks a lot for your help!
I will try to reproduce it with pure ROOT (no dd4hep). 
Otherwise I cannot file a bug report if the problem is not in dd4hep itself.
I am afraid it will take a bit.

**Comment by MarkusFrankATcernch** [comment] 2023-08-02 15:33
I discussed with the ROOT guys. To handle the transparency for volumes properly changes in ROOT shall be required.
This will take a while -- and once I made the MR in ROOT a new ROOT version -- I am afraid.

**Comment by MarkusFrankATcernch** [comment] 2023-08-04 14:27
This PR https://github.com/root-project/root/pull/13402 should eventually fix the problem.

**Comment by MarkusFrankATcernch** [comment] 2023-12-14 12:04
Assumed fixed with latest ROOT. Closed due to no reaction.

**Closed by MarkusFrankATcernch** 2023-12-14 12:04 UTC
Labels: bug, work in progress, Testing, Fixed
