### ISSUE TITLE
cannot compile DD4hep/examples on lxplus?

### ISSUE THREAD

**Issue by albertobelloni** [AIDASoft/DD4hep#1008] opened 2022-11-07 16:01 UTC
Dear all,

let me report an issue I am encountering when I try to compile the examples/ area. I hope I am committing a very simple mistake! Let me also note that I normally use zsh, but I believe I tried using bash, with similar results.

 - OS version: centos7 on lxplus7
 - Compiler version: GCC 11.1.0
 - Package version: commit 136b80877667f3f33be3f4a1afc45a22f3cfd976
 - Reproduced by (let me note that compiling DD4hep is probably not necessary, as the problem appears when running CMake to build the examples):
   ssh lxplus
   git checkout https://github.com/AIDASoft/DD4hep.git
   source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/setup.sh
   cd DD4hep
   mkdir build && cd build
   cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release ..
   cmake -j4
   cd ../examples
   mkdir build && cd build
   cmake ..

 - Output: the build runs ok, the issue comes when I use "cmake .." in examples/build:

```
% cmake ..
-- Including DD4hepBuild.cmake
CMake Warning (dev) at /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/cmake/DD4hepBuild.cmake:768 (try_compile):
  try_compile given unknown argument "False".
Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/cmake/DD4hepConfig.cmake:48 (DD4HEP_SETUP_BOOST_TARGETS)
  CMakeLists.txt:35 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /afs/cern.ch/user/a/abelloni/work/AIDA_DD4hep/DD4hep/examples/build/try/CMakeFiles/CMakeTmp/CMakeLists.txt:16 (add_executable):
  CXX_STANDARD is set to invalid value 'CXX_EXTENSIONS'


CMake Error at /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/cmake/DD4hepBuild.cmake:768 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-centos7-gcc11-opt/cmake/DD4hepConfig.cmake:48 (DD4HEP_SETUP_BOOST_TARGETS)
  CMakeLists.txt:35 (find_package)


-- Configuring incomplete, errors occurred!
See also "/afs/cern.ch/user/a/abelloni/work/AIDA_DD4hep/DD4hep/examples/build/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log](https://github.com/AIDASoft/DD4hep/files/9953359/CMakeOutput.log)

 - Goal: I would like to compile the examples directory; my ultimate goal is to create my own detector configuration and compile it using the DD4hep installation in lxplus (i.e., I would like to _not_ checkout the whole DD4hep repository, but just compile my example using the pre-installed DD4hep on lxplus).

Thank you very much for any suggestion. Best,
Alberto

**Comment by andresailer** [comment] 2022-11-07 16:13
Hi @albertobelloni 

I think this should be fixed by sourcing the `bin/thisdd4hep.sh` from your installation before cmaking/building the examples.
Is that just a typo in your reproducer you have `cmake -j4`, this is just `make -j4`, right?
You probably have to first `make install` as well though.

If you want to make your own dd4hep-based package, then you can also have a look at slide 21ff from https://indico.cern.ch/event/1182767/contributions/5093486/attachments/2532164/4356996/221020_soft_tutorial_dd4hep.pdf
Which contains the minimal cmake and cpp code for a geometry driver.

If you move to LCG_102b
`source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh`
You will get a more recent DD4hep.

Cheers,
Andre

**Comment by albertobelloni** [comment] 2022-11-08 09:13
Dear Andre,

thank you very much for your prompt input (and for pointing out the typos). I did get further ahead, but still had some troubles with generating Makefile's. Let me note that this time I checked out the tagged v01-23 version of DD4hep, and followed your suggestion to use a newer LCG view. Here are the commands I used:

- OS version: centos7 on lxplus7

- Compiler version: GCC 11.3.0

- Package version: tags/v01-23

- Reproduced by:

  ssh lxplus
  mkdir AIDA && cd AIDA
  source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh
  git clone https://github.com/AIDASoft/DD4hep.git
  git checkout tags/v01-23
  cd DD4hep
  mkdir build && cd build
  cmake -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=ON -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release ..
  make -j4
  make install
  source ./bin/thisdd4hep.sh
  cd ../examples
  mkdir build && cd build
  cmake ..

- Output:

CMake Error at /afs/cern.ch/user/a/abelloni/work/AIDA/DD4hep/build/DD4hepConfig.cmake:37 (include):
  include could not find requested file:

    /afs/cern.ch/user/a/abelloni/work/AIDA/DD4hep/build/cmake/DD4hep.cmake
Call Stack (most recent call first):
  CMakeLists.txt:35 (find_package)


-- DD4hep uses Geant4
-- Found XercesC: /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/libxerces-c.so (found suitable version "3.2.3", minimum required is "3.2.3")
-- Detected Compiler: GCC 11.3.0
-- Detected CPU: broadwell
-- Found XercesC: /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/lib/libxerces-c.so (found version "3.2.3")
CMake Error at /afs/cern.ch/user/a/abelloni/work/AIDA/DD4hep/build/DD4hepConfig.cmake:56 (DD4HEP_SETUP_GEANT4_TARGETS):
  Unknown CMake command "DD4HEP_SETUP_GEANT4_TARGETS".
Call Stack (most recent call first):
  CMakeLists.txt:35 (find_package)


-- Configuring incomplete, errors occurred!
See also "/afs/cern.ch/user/a/abelloni/work/AIDA/DD4hep/examples/build/CMakeFiles/CMakeOutput.log".
See also "/afs/cern.ch/user/a/abelloni/work/AIDA/DD4hep/examples/build/CMakeFiles/CMakeError.log".
[CMakeError.log](https://github.com/AIDASoft/DD4hep/files/9959489/CMakeError.log)
[CMakeOutput.log](https://github.com/AIDASoft/DD4hep/files/9959490/CMakeOutput.log)

I also tried the following line, just to make sure GEANT4 is properly configured:

  cd /cvmfs/sft.cern.ch/lcg/releases/Geant4/11.0.3-e531e/x86_64-centos7-gcc11-opt/bin/; source geant4.sh; cd -

Sorry for bothering, this seems to be a rather trivial issue. Best,
Alberto

**Comment by andresailer** [comment] 2022-11-08 09:29
Hi Alberto,

The first cmake command must have also the option `-D CMAKE_INSTALL_PREFIX=somewhere/you/can/write`, otherwise I don't imagine  `make install` is actually successful?

And then `source /somewhere/you/can/write/bin/thisdd4hep.sh`

If you use 102b you don't have to compile DD4hep yourself, especially if you go for DD4hep 1.23, because that is part of 102b. 
You could go directly for compiling the examples then.

```
source /cvmfs/sft.cern.ch/lcg/views/LCG_102b/x86_64-centos7-gcc11-opt/setup.sh
git clone https://github.com/AIDASoft/DD4hep.git
cd DD4hep
git checkout tags/v01-23
cd examples
mkdir build
cd build
cmake ..
make
```

works for me on lxplus.

Cheers,
Andre

**Comment by albertobelloni** [comment] 2022-11-08 13:12
Dear Andre,

thank you very much again; your instructions worked, and indeed the examples compiled properly. I suspect I (uselessly) ended up taking the long road, as I ultimately just wanted to do as you suggest: compile only the examples against the pre-installed dd4hep version, without the need to checkout the source code of dd4hep. Thank you again! Best,
Alberto

**Comment by andresailer** [comment] 2022-11-09 12:13
Great!

**Closed by andresailer** 2022-11-09 12:13 UTC
Labels: bug
