### ISSUE TITLE
error w/ units in ddsim  

### ISSUE THREAD

**Issue by gaede** [AIDASoft/DD4hep#479] opened 2019-01-31 10:52 UTC
Hi all,

haven't run ddsim in a recent version of DD4hep in a while. I get the following error:

```
11:43:41-gaede~/test/photons/production$ ddsim   --inputFiles mcparticles.slcio   --outputFile gamma_200GeV_35deg.slcio   --compactFile $lcgeo_DIR/ILD/compact/ILD_l5_v02/ILD_l5_v02.xml   --numberOfEvents 3   --steeringFile ddsim_steer.py
DEPRECATION WARNING  The namespace "SystemOfUnits" is deprecated. Please use "g4units" instead.
DEBUG: Importing units into namespace units
Traceback (most recent call last):
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/bin/ddsim", line 16, in <module>
    RUNNER.run()
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/DDSim/DD4hepSimulation.py", line 282, in run
    import DDG4, dd4hep
  File "/data/ilcsoft/HEAD/root/6.14.06/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/DDG4.py", line 12, in <module>
    from dd4hep_base import *
  File "/data/ilcsoft/HEAD/root/6.14.06/lib/ROOT.py", line 461, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 304, in <module>
    import_units(ns=units)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 297, in import_units
    import_unit(ns, u)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 250, in import_unit
    setattr(ns,nam,getattr(core,nam))
AttributeError: type object 'dd4hep' has no attribute 'nanometer'

```

Am I missing sth. ?
Should  it work on MacOs ?

 - OS version: MacOS 10.14 Mojave
 - Compiler version: Apple LLVM version 10.0.0 (clang-1000.10.44.4)
 - DD4hep version: github HEAD (03.01.2019)

**Comment by andresailer** [comment] 2019-02-04 09:58
At the top of your ddsim_steer.py there is `from ??Units?? import GeV, ...`, add the units you need.
If that doesn't solve the problem, please attach or link to the ddsim_steer.py

**Comment by MarkusFrankATcernch** [comment] 2019-02-14 14:48
As  agreed during meeting. Closing issue.

**Comment by gaede** [comment] 2019-02-18 14:09
I have made a complete fresh install of iLCsoft (including geant4, ROOT, etc) with todays HEAD versions and get the same problem (see below). So I reopened this issue. 

Any hint from anybody that has gotten a recent version of DD4hep working on MacOS w/ Mojave would be highly appreciated.

```
15:04:51-gaede~/lcgeo/workDir$ ddsim --steeringFile ./ddsim_steer_new.py --inputFile ./mcparticles_single_muon_5GeV_85deg.slcio --compact /data/ilcsoft/HEAD/lcgeo/HEAD/ILD/compact/ILD_l5_v02/ILD_l5_v02.xml --outputFile bla_42.slcio
DEBUG: Importing units into namespace units
Traceback (most recent call last):
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/bin/ddsim", line 16, in <module>
    RUNNER.run()
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/DDSim/DD4hepSimulation.py", line 282, in run
    import DDG4, dd4hep
  File "/data/ilcsoft/HEAD/root/6.16.00/lib/ROOT.py", line 463, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/DDG4.py", line 12, in <module>
    from dd4hep_base import *
  File "/data/ilcsoft/HEAD/root/6.16.00/lib/ROOT.py", line 463, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 304, in <module>
    import_units(ns=units)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 297, in import_units
    import_unit(ns, u)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 250, in import_unit
    setattr(ns,nam,getattr(core,nam))
AttributeError: type object 'dd4hep' has no attribute 'nanometer'

```

**Comment by petricm** [comment] 2019-02-18 14:56
Can you please attach the `ddsim_steer_new.py` and provide an example with the particle gun, so that this is easy reproducible.

**Comment by gaede** [comment] 2019-02-18 15:07
This is independent of the actual steering, same problem with gun, e.g:
```
ddsim --enableGun  --compact /data/ilcsoft/HEAD/lcgeo/HEAD/ILD/compact/ILD_l5_v02/ILD_l5_v02.xml --numberOfEvents 3
```

**Comment by andresailer** [comment] 2019-02-18 16:52
what happens if you do:
```
python -i
import dd4hep
```
Have you tried with an earlier version of root?
What is the python version?

**Comment by gaede** [comment] 2019-02-19 13:18
The same problem occurs (so it is not ddsim), however different stack trace (w/o ROOT.py):
```
Python 2.7.10 (default, Aug 17 2018, 19:45:58) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dd4hep
DEBUG: Importing units into namespace units
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep.py", line 11, in <module>
    from dd4hep_base import *
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 304, in <module>
    import_units(ns=units)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 297, in import_units
    import_unit(ns, u)
  File "/data/ilcsoft/HEAD/DD4hep/HEAD/python/dd4hep_base.py", line 250, in import_unit
    setattr(ns,nam,getattr(core,nam))
AttributeError: type object 'dd4hep' has no attribute 'nanometer'

```

**Comment by andresailer** [comment] 2019-02-20 09:10
This are the minimal steps on my machine and installation to get the same error message, but also the successful adding of 'nanometer' to the object, reproducing what happens in dd4hep_base.
Save as script and execute:
```python
#!/bin/env python

from ROOT import gSystem
import platform
if platform.system()=="Darwin":
  gSystem.SetDynamicPath(os.environ['DD4HEP_LIBRARY_PATH'])
print 'loaded DDCore? ', gSystem.Load('libDDCore')
from ROOT import dd4hep
print "dd4hep class type", repr(dd4hep)
print "dd4hep attributes", dir(dd4hep) # note there is no 'nanometer' at this point
tools = getattr(dd4hep, 'tools')
print tools

def fail():
  print "nanometer",  getattr(dd4hep, 'nanometer')

def success():
  print "Adding Evaluator to tools", getattr(tools, 'Evaluator')
  print "nanometer",  getattr(dd4hep, 'nanometer')

if __name__ == '__main__':
  try:
    fail()
  except Exception as e:
    print "EXCEPTION", e
  success()
```

Output for me:
```
$ python testdd.py
loaded DDCore?  0
dd4hep class type <class 'ROOT.dd4hep'>
dd4hep attributes ['ALWAYS', 'DEBUG', 'ERROR', 'FATAL', 'INFO', 'NOLOG', 'VERBOSE', 'WARNING', '__add__', '__bool__', '__class__', '__cppname__', '__delattr__', '__destruct__', '__dict__', '__dispatch__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__nonzero__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__scope__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', '_get_smart_ptr']
<class 'ROOT.dd4hep.tools'>
nanometer EXCEPTION type object 'dd4hep' has no attribute 'nanometer'
Adding Evaluator to tools <class 'ROOT.dd4hep.tools.Evaluator'>
nanometer 1e-07
```
I think on your system this should fail also in success.
Not that I understand what is happening in detail, but at least we might narrow down where the problem happens.

**Comment by gaede** [comment] 2019-02-20 13:35
As you predicted  - here is my output (after adding `import os`):
```
11:15:44-gaede~/python$ python ./dd4hep_python_issue.py 
loaded DDCore?  0
dd4hep class type <class 'ROOT.dd4hep'>
dd4hep attributes ['ALWAYS', 'DEBUG', 'ERROR', 'FATAL', 'INFO', 'NOLOG', 'VERBOSE', 'WARNING', '__add__', '__bool__', '__class__', '__cppname__', '__delattr__', '__destruct__', '__dict__', '__dispatch__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__nonzero__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__scope__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', '_get_smart_ptr']
<class 'ROOT.dd4hep.tools'>
nanometer EXCEPTION type object 'dd4hep' has no attribute 'nanometer'
Adding Evaluator to tools <class 'ROOT.dd4hep.tools.Evaluator'>
nanometer
Traceback (most recent call last):
  File "./dd4hep_python_issue.py", line 31, in <module>
    success()
  File "./dd4hep_python_issue.py", line 24, in success
    print "nanometer",  getattr(dd4hep, 'nanometer')
AttributeError: type object 'dd4hep' has no attribute 'nanometer'

```

**Comment by petricm** [comment] 2019-07-10 14:11
I could now test on mac 10.14 and I cannot reproduce @gaede issues 

```
2019-07-10 16:07 lcdci@pclcdmac01:DD4hep (master)$ python testdd.py
loaded DDCore?  0
dd4hep class type <class 'ROOT.dd4hep'>
dd4hep attributes ['ALWAYS', 'DEBUG', 'ERROR', 'FATAL', 'INFO', 'NOLOG', 'VERBOSE', 'WARNING', '__add__', '__bool__', '__class__', '__cppname__', '__delattr__', '__destruct__', '__dict__', '__dispatch__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__nonzero__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__scope__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__weakref__', '_get_smart_ptr']
<class 'ROOT.dd4hep.tools'>
nanometer EXCEPTION type object 'dd4hep' has no attribute 'nanometer'
Adding Evaluator to tools <class 'ROOT.dd4hep.tools.Evaluator'>
nanometer 1e-07
```

**Comment by petricm** [comment] 2019-07-10 14:21
Which python are you using to run this?
I see this `Python 2.7.10 (default, Aug 17 2018, 19:45:58) ` and this seems to me as system python, and we know the system python is under SIP and does not work.

**Comment by gaede** [comment] 2019-08-08 15:05
@petricm: yes I used the system python (as in the pas w/o problems). Also tried using a python from homebrew (2.7.16) and still the same problem.
Which python did you use on your mac - and how did you build ROOT then with this ?

**Comment by petricm** [comment] 2019-08-12 08:43
DD4hep does not work with the system python on mac, because of the system integrity protection since version 10.11 El Capitan. With work I mean that all tests pass, there is a functioning subset of features that work, but not everything.

If you use the python from homebrew, you need to compile ROOT from source, as I am not sure that the two pythons (system and homebrew) are compatible (the dictionaries) and the binaries provided by ROOT are based on the system python.

I built python from source, this takes 5 min, then I install pip and numpy as it is requred for ROOT. You add this python to the path and the ROOT cmake will pick it up.

You could also try to either mount `/cvmfs/clicdp.cern.ch` on the mac are initialize with `init_mac.sh` or copy the required binaries from there.

**Comment by gaede** [comment] 2019-08-12 14:44
Ok thanks. In the meantime I had managed to create one DD4hep build where the DDG4-Python actually did work - however this was after a lot of switching between system python and brew python. So I will start again from scratch w/ building ROOT and the brew python. 
Anyways, will close this issue, as it seems to be not (entirely) related to DD4hep.
PS: of course I have always deactivated SIP on my Mac ;-)

**Closed** 2019-08-12 14:45 UTC
Labels: question
