### ISSUE TITLE
Empty rootmap file when using v01-02

### ISSUE THREAD

**Issue by jhrdinka** [AIDASoft/DD4hep#228] opened 2017-09-12 12:03 UTC
When trying to run an example which builds a dd4hep detector in our framework the generated rootmap (which is created using dd4hep_generate_rootmap) is empty and therefore the detector constructors are not found. 
We are using the new DD4hep version 01-02.
We got this problem on two different slc6 machines using the LCG release 90a and on OSX.

**Comment by andresailer** [comment] 2017-09-12 12:22
As this is most likely this is an issue of the environment, LD_LIBRARY_PATH, used when the dd4hep macro is called, you have to provide all the steps that lead to this problem: `git clone, source /cvmfs/..../setup.sh, cmake ... ???`

**Comment by petricm** [comment] 2017-09-12 12:22
On macOS if you have SIP enabled DD4hep only works with a non-system python. Provide on for the mac case also `which python` and OS version.

**Comment by jhrdinka** [comment] 2017-09-12 12:32
For the slc6 machines we are using DD4hep from here:  /cvmfs/sft.cern.ch/lcg/releases/LCG_90a/DD4hep/01-02/x86_64-slc6-gcc62-opt 
setting it up with bin/thisdd4hep.sh of this repository.
The LD_LIBRARY_PATH is set correctly to our library directory.  You can find the CMakeList where the rootmap is generated here: https://gitlab.cern.ch/acts/acts-test-fw/blob/master/Detectors/DD4hepDetector/CMakeLists.txt
If you want to I can send you full instructions to setup acts and our test framework.

**Comment by andresailer** [comment] 2017-09-12 12:36
Yes, please send the full instructions.

**Comment by jhrdinka** [comment] 2017-09-12 12:43
First you need to set up our core repository:
```
git clone https://:@gitlab.cern.ch:8443/acts/a-common-tracking-sw.git
setup the environment:
export lcgversion=LCG_90a
export platform=x86_64-slc6-gcc62-opt
export lcgdir=/cvmfs/sft.cern.ch/lcg/views/${lcgversion}/${platform}
export actsbase=${PWD}
source ${lcgdir}/setup.sh
cd /cvmfs/sft.cern.ch/lcg/releases/${lcgversion}/DD4hep/01-02/${platform} && source bin/thisdd4hep.sh && cd ${actsbase}
```
build it
```
mkdir build; cd build;
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/installed -DEIGEN_INCLUDE_DIR=${lcgdir}/include/eigen3/ -DBOOST_INCLUDEDIR=${lcgdir}/include/boost/ -DBUILD_TGEO_PLUGIN=ON -DBUILD_DD4HEP_PLUGIN=ON
make install
```

**Comment by jhrdinka** [comment] 2017-09-13 07:59
Here are the full instruction if you have access to cvmfs, otherwise you need to replace the paths with your local paths:
`# Clone the framework
# It includes the core repository which is a git submodule
git clone https://:@gitlab.cern.ch:8443/acts/acts-framework.git
cd acts-framework
# Get the submodules
git submodule update --init
# Setup the environment
export actsfw=${PWD}
export actscore=${PWD}/external/acts-core
export lcgversion=LCG_90a
export platform=x86_64-slc6-gcc62-opt
export lcgdir=/cvmfs/sft.cern.ch/lcg/views/${lcgversion}/${platform}
source ${lcgdir}/setup.sh
cd /cvmfs/sft.cern.ch/lcg/releases/${lcgversion}/DD4hep/01-02/${platform} && source bin/thisdd4hep.sh && cd ${actsfw}
export LD_LIBRARY_PATH=${actsfw}/build/installed/lib64/:${actsbase}/build/installed/lib64/:$LD_LIBRARY_PATH
# Build the core
cd ${actscore}
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/installed -DEIGEN_INCLUDE_DIR=${lcgdir}/include/eigen3/ -DBOOST_INCLUDEDIR=${lcgdir}/include/boost/ -DBUILD_TGEO_PLUGIN=ON -DBUILD_DD4HEP_PLUGIN=ON
make -j 8 install
# Build the framework
cd $actsfw
mkdir build
cd build
cmake .. -DACTS_DIR=${actsbase}/build/installed/share/cmake/ACTS/  -DCMAKE_PREFIX_PATH="/${actscore}/build/installed" -DCMAKE_INSTALL_PREFIX=$PWD/installed -DUSE_DD4HEP=ON
make -j 8 install
# Run the example
cd $actsfw
./build/bin/ACTFWDD4hepGeometryExample`

**Comment by andresailer** [comment] 2017-09-13 09:22
The library is created in `../../lib64`, and not were the listcomponents command is run.
```
$ make ACTFWDD4hepDetector
[ 35%] Built target ACTFramework
Scanning dependencies of target ACTFWDD4hepDetector
[ 40%] Building CXX object Detectors/DD4hepDetector/CMakeFiles/ACTFWDD4hepDetector.dir/src/AirTube_geo.cpp.o
[ 45%] Linking CXX shared library ../../lib64/libACTFWDD4hepDetector.so
--  *** Gaudi listcomponents: Generate map for libACTFWDD4hepDetector.so ...
--  *** MakeGaudiMap.cmake run command : /cvmfs/sft.cern.ch/lcg/views/LCG_90a/x86_64-slc6-gcc62-opt/bin/listcomponents -o libACTFWDD4hepDetector.components libACTFWDD4hepDetector.so
                 WORKING_DIRECTORY /data/sailer/temp/actsTests/acts-framework/build/Detectors/DD4hepDetector
ERROR: failed to load libACTFWDD4hepDetector.so
libACTSDD4hepPlugin.so: cannot open shared object file: No such file or directory
[100%] Built target ACTFWDD4hepDetector
```
So create the library where the listcomponents is going to be run?

**Comment by jhrdinka** [comment] 2017-09-13 11:20
We just create our libraries using global environmental variables (so depending on the archetecture the libraries will be build in different library directories, e.g. we also tried on mac and we get the same problem there, although it is in another library directory). I think the problem is that the path here is hardcoded: https://github.com/AIDASoft/DD4hep/blob/master/cmake/MakeGaudiMap.cmake#L5

**Comment by andresailer** [comment] 2017-09-13 11:29
The problem is _not_ finding the listcomponents program, which is what is done in the line you link.
The problem is that `libACTFWDD4hepDetector.so` is not in the WorkingDirectory `build/Detectors/DD4hepDetector`
Because the error message is quite clear
```
libACTSDD4hepPlugin.so: cannot open shared object file: No such file or directory
```

**Comment by andresailer** [comment] 2017-09-13 11:41
https://gitlab.cern.ch/acts/acts-framework/merge_requests/65

**Comment by jhrdinka** [comment] 2017-09-13 14:59
This still does not work for me, I get the following error message:
[ 82%] Linking CXX shared library libACTFWDD4hepDetector.so
--  *** Gaudi listcomponents: Generate map for libACTFWDD4hepDetector.so ...
--  *** MakeGaudiMap.cmake run command : /cvmfs/sft.cern.ch/lcg/views/LCG_90a/x86_64-slc6-gcc62-opt/bin/listcomponents -o libACTFWDD4hepDetector.components libACTFWDD4hepDetector.so
                 WORKING_DIRECTORY
CMake Error at /cvmfs/sft.cern.ch/lcg/releases/LCG_90a/DD4hep/01-02/x86_64-slc6-gcc62-opt/cmake/MakeGaudiMap.cmake:17 (EXECUTE_PROCESS):
  execute_process called with no value for WORKING_DIRECTORY.


make[2]: *** [Detectors/DD4hepDetector/libACTFWDD4hepDetector.so] Error 1

**Comment by andresailer** [comment] 2017-09-13 15:20
Updated my PR for ACTS, now it should be working

**Comment by jhrdinka** [comment] 2017-09-14 08:32
It is working now, thanks

**Comment by petricm** [comment] 2017-09-14 08:34
Resolved by [bug fix](https://gitlab.cern.ch/acts/acts-framework/merge_requests/65) in ACTS

**Closed by petricm** 2017-09-14 08:34 UTC
